---
- name: Variables Demo
  hosts: Group1
  become: yes
  vars:
   myusername: Vivich007
   mywelcomemessage: Happy to see you!

  tasks:
  - name: Update Dynamic Page
    copy:
     src: static.html
     dest: /var/www/html/static.html
...