---
- name: Variables Demo
  hosts: Group1
  become: yes
  vars:
   myusername: Vivich007
   mywelcomemessage: Happy to see you!

  tasks:
  - name: Update Dynamic Page
    template:
     src: dynamic.j2
     dest: /var/www/html/dynamic.html
     force: yes
...