---
- name: Ensure System Packages Updated
  yum:
    update_cache: yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

- name: Ensure System Packages Updated
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Install httpd
  yum:
    name: httpd
    state: present
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

- name: Start httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "CentOS" or ansible_distribution == "Amazon"

- name: Install apache2
  apt:
    name: apache2
    state: present
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

- name: Start apache2
  service:
    name: apache2
    enabled: yes
  when: ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"

...
